#!/bin/bash

echo "🚀 Nova - GitHub Setup Instructions"
echo ""
echo "Your local repository is ready! Follow these steps to publish to GitHub:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   Go to: https://github.com/new"
echo "   Repository name: nova"
echo "   Description: Fast, minimal AI chatbot with RAG and web search"
echo "   Visibility: Public (or Private)"
echo "   DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. Once created, run these commands:"
echo ""
echo "   cd /Users/sures/Downloads/bored"
echo "   git remote add origin https://github.com/YOUR_USERNAME/nova.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Update the README.md with your actual GitHub username"
echo ""
echo "✅ Your local repository has been initialized with:"
echo "   - 40 files committed"
echo "   - .gitignore files (excludes venv, node_modules, .env)"
echo "   - Comprehensive README.md"
echo ""
